### ISSUE TITLE
default password

### ISSUE THREAD

**Issue by omb7141980** [MrHacker-X/KalnemiX#2]
When I run kalnemix.py from termux everything starts fine but its asking for a password to continue. 
~/KalnemiX $ sudo python kalnemix.py
[✔] Internet Connectivity: Done
[+] Enter the password:
[~] Password Verifying...

[✘] Access denied

Press ENTER To Get Password

When I press enter it just shuts down and puts me back to termux. What is tbe default password?

**Comment by MrHacker-X** [comment]
Password is wowx

**Comment by omb7141980** [comment]
> Password is wowx

yes thx
